add utility commands

diff --git a/bin/portforward b/bin/portforward
--- a/bin/portforward
+++ b/bin/portforward
@@ -1,7 +1,8 @@
 #!/bin/bash
 
 if [[ -z "${REMOTE_USER}" ]] || [[ -z "${REMOTE_HOST}" ]] || [[ -z "${SSH_PRIVATE_KEY}" ]]; then
-  exit
+  echo "REMOTE_USER, REMOTE_HOST and SSH_PRIVATE_KEY are required"
+  exit 1
 fi
 
 ssh -i ${SSH_PRIVATE_KEY} -L 7189:localhost:7189 -N -o "StrictHostKeyChecking no" -o "AddressFamily inet" ${REMOTE_USER}@${REMOTE_HOST} 2>/dev/null &
